name: Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  Tests:
    strategy:
      matrix:
        xcode_version: ["15.4", "16.0"]
    env: 
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer"
    runs-on: macos-14
    steps:
      - name: Get swift version
        run: swift --version
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          swift test
